### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by codehangen** [falsisdev/fseasy#10]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by falsisdev** [comment]
Thanks for this request. I'm glad to hear that. If the project was active, we would really need your help. But unfortunately, our project is inactive and its development stopped. 

However, since the Github repository is open, you can change the source codes if you want and send it to us as a pull request. We can evaluate your request and add it to the project. Maybe our project will be active again in future.

**Comment by falsisdev** [comment]
Sorry, this project is permanently disabled.
